カレンダープログラムを作成しました
sht3ng/ruby-practices pull request #2
Opened 2021-09-24 06:40 UTC by naganoshunta

ご確認どうかよろしくお願いいたします。

2021-09-24 07:26 UTC, naganoshunta commented
このプルリクエストには3つコミットがあります。
一つ目のコミットはメソッドに処理をまとめず，処理のまとまりをべた書きしている段階で，
二つ目のコミットは処理のまとまりをメソッドにまとめた段階で，
三つ目のコミットはメソッドと変数をクラスにまとめた段階のものです。

処理のまとまりをメソッドにまとめるときはどこからどこまでを一つのメソッドにするかが悩ましく，
メソッドと変数をクラスにまとめるときはどのようにクラスにまとめるかがとても悩ましかったです。
おかしなところもあると思いますが，ご確認のほどよろしくお願いいたします。

2021-09-27 04:15 UTC, naganoshunta commented
レビュワーの方へ
「naganoshunta force-pushed the calendar  branch from 832a4f9 to 0739f91」の履歴につきまして，
02.calendar/calendar.rb の42行目`private`の下に改行を入れただけの変更をVSCodeからgit commit --amendした結果，
Merge Commitが作成されてしまいこちらをgit reset --hard 0739f91 && git push --force-with-leaceコマンドによって
取り消そうとした履歴です。こちらの履歴によって，改行以外にはコード自体に変更は加えられていません。
コミット履歴が汚れてしまって大変申し訳ありませんが，よろしくお願いいたします。

2021-09-27 04:29 UTC, naganoshunta commented on 02.calendar/calendar.rb
> +  private
レビュワーの方へ
「naganoshunta force-pushed the calendar  branch from 832a4f9 to 0739f91」の履歴につきまして，
02.calendar/calendar.rb の42行目`private`の下に改行を入れただけの変更をVSCodeからgit commit --amendした結果，
Merge Commitが作成されてしまいこちらをgit reset --hard 0739f91 && git push --force-with-leaceコマンドによって
取り消そうとした履歴です。こちらの履歴によって，改行以外にはコード自体に変更は加えられていません。
コミット履歴が汚れてしまって大変申し訳ありませんが，よろしくお願いいたします。

2021-09-29 12:47 UTC, u1tnk requested changes
もうほとんどオブジェクト指向ですね 👍 
コメントしたところ見直してみてください。

2021-09-29 12:47 UTC, u1tnk commented on 02.calendar/calendar.rb
> +    opts.on('-m', '--month MONTH', /(^[1-9]$)|(^1[0-2]$)/, Integer) do |month|
こだわりの正規表現ですね 👍

2021-09-29 12:47 UTC, u1tnk commented on 02.calendar/calendar.rb
> +  attr_reader :today, :validity, :first_day, :last_day, :year, :month, :date_table, :calendar
このプラクティスだと気にする必要は無いのですが、オブジェクト指向的には外部からアクセスされないものには attr_readerは付けない方が良いですよ。

2021-09-29 12:47 UTC, u1tnk commented on 02.calendar/calendar.rb
> +    @calendar = [
Calendarクラスに `@calendar` 変数があるのはちょっと混乱してしまいますね。
また、変数名を変更するより、outputから呼び出されたときにこの文字列を返すようにすれば良いと思います。
一時的に保存する必要の無いものは呼び出されたときに生成すると良いですよ。

2021-09-29 12:47 UTC, u1tnk commented on 02.calendar/calendar.rb
> +    "\e[7m#{string}\e[0m"
歓迎要件 👍

2021-09-29 14:35 UTC, naganoshunta commented on 02.calendar/calendar.rb
> +    opts.on('-m', '--month MONTH', /(^[1-9]$)|(^1[0-2]$)/, Integer) do |month|
ありがとうございます！☺️

2021-09-29 14:40 UTC, naganoshunta commented on 02.calendar/calendar.rb
> +  attr_reader :today, :validity, :first_day, :last_day, :year, :month, :date_table, :calendar
ありがとうございます！とても勉強になります！😄
なんとなくつくったインスタンス変数はattr_readerなどに書いておかないといけないのかなと思い込んでいました！
使わないものはちゃんとしまっておかないといけないのですね！

2021-09-29 14:44 UTC, naganoshunta commented on 02.calendar/calendar.rb
> +    @calendar = [
こちらもとても勉強になりました！☺️
出力用の文字列は保存する必要ないものですね！
自分でも気づかないうちに変数に代入することに考えが固着していたように思います！

2021-09-29 14:45 UTC, naganoshunta commented on 02.calendar/calendar.rb
> +    "\e[7m#{string}\e[0m"
ありがとうございます！☺️

2021-09-29 15:11 UTC, naganoshunta commented
@u1tnk さん
レビューしてくださりありがとうございました！
とても勉強になりました！😄
レビューいただいた内容をもとにコードを修正したコミットをpushいたしました！
今回の変更で出力用の文字列をoutputメソッド内で生成して戻り値にするように変更して外部でprintメソッドに渡すようにしたのですが，
printメソッドは外部で呼び出す形で問題なかったでしょうか。
お手数おかけして恐縮ですがご確認のほどどうかよろしくお願いいたします。

2021-09-30 01:12 UTC, u1tnk approved these changes
色々スッキリしましたね 👍 

> printメソッドは外部で呼び出す形で問題なかったでしょうか。

はい、そちらの方がクラスの責務が減って良いと思いますよ。
ただ、 `output`というメソッドで文字列が返ってくるのもアリなレベルですが、 `to_s`とか`format`とかの方が分かりやすいかと思います。

そこは修正はお任せできるレベルなのでapproveです 🙆‍♀️

2021-09-30 01:55 UTC, naganoshunta commented
レビューありがとうございます！☺️
基本的にクラスの責任はできるだけ小さくする方がよいのですね！勉強になりました！

> outputというメソッドで文字列が返ってくるのもアリなレベルですが、 to_sとかformatとかの方が分かりやすいかと思います。

どんなクラスのオブジェクトが戻り値として返ってくるかも考慮してメソッド名を考える必要があるのですね！
こちらも修正させていただきました！

お時間をとってみていただいてありがとうございました！☺️🙇‍♂️

2021-10-01 05:33 UTC, merged